export const INITIAL_CHALLENGES = [
  {
    id: 1,
    title: "Bike to Work Week",
    description: "Use a bicycle or walk for your commute at least 3 days this week.",
    category: "transport",
    points: 50,
    carbonSaved: 12.5,
    daysLeft: 5,
    completed: false,
  },
  {
    id: 2,
    title: "Meatless Monday",
    description: "Skip meat for all meals on Monday and try plant-based alternatives.",
    category: "food",
    points: 30,
    carbonSaved: 4.2,
    daysLeft: 3,
    completed: false,
  },
  {
    id: 3,
    title: "Unplug & Save",
    description: "Unplug idle electronics and use smart power strips for 7 days.",
    category: "electricity",
    points: 25,
    carbonSaved: 3.8,
    daysLeft: 6,
    completed: false,
  },
  {
    id: 4,
    title: "Public Transit Challenge",
    description: "Take public transport instead of driving for 5 commutes this week.",
    category: "transport",
    points: 40,
    carbonSaved: 9.0,
    daysLeft: 4,
    completed: true,
  },
  {
    id: 5,
    title: "Zero-Waste Shopping",
    description: "Bring reusable bags and avoid single-use packaging on your next 3 shopping trips.",
    category: "shopping",
    points: 20,
    carbonSaved: 2.1,
    daysLeft: 7,
    completed: false,
  },
  {
    id: 6,
    title: "AC Thermostat Boost",
    description: "Raise your AC thermostat by 2°C for the entire week.",
    category: "electricity",
    points: 35,
    carbonSaved: 6.5,
    daysLeft: 5,
    completed: false,
  },
];

export const LEADERBOARD = [
  { rank: 1, username: "GreenGuru", points: 2840, carbonSaved: 892, streak: 45, badge: "Climate Hero", avatar: "" },
  { rank: 2, username: "EcoNova", points: 2650, carbonSaved: 810, streak: 38, badge: "Eco Warrior", avatar: "" },
  { rank: 3, username: "EcoChampion", points: 2480, carbonSaved: 765, streak: 7, badge: "Green Beginner", avatar: "" },
  { rank: 4, username: "LeafLover", points: 2210, carbonSaved: 698, streak: 22, badge: "Streak Master", avatar: "" },
  { rank: 5, username: "CarbonCut", points: 1980, carbonSaved: 620, streak: 15, badge: "Eco Warrior", avatar: "" },
  { rank: 6, username: "SustainSam", points: 1750, carbonSaved: 540, streak: 12, badge: "Green Beginner", avatar: "" },
  { rank: 7, username: "PlanetPat", points: 1620, carbonSaved: 498, streak: 9, badge: "Tree Planter", avatar: "" },
  { rank: 8, username: "ZeroWasteZoe", points: 1490, carbonSaved: 455, streak: 18, badge: "Eco Warrior", avatar: "" },
];

export const TEMPLATE_RECOMMENDATIONS = [
  {
    id: 1,
    category: "Transport",
    insight: "Transportation accounts for the largest portion of most users' carbon footprint.",
    suggestion: "Use a bicycle or walk for distances under 5 km. Consider carpooling for longer commutes.",
    estimatedCarbonSaving: 18.5,
    priority: "high",
  },
  {
    id: 2,
    category: "Electricity",
    insight: "Reducing AC usage by just 2 hours per day can save significant emissions each month.",
    suggestion: "Set your AC thermostat to 24°C or higher. Use ceiling fans as a supplement.",
    estimatedCarbonSaving: 12.0,
    priority: "high",
  },
  {
    id: 3,
    category: "Food",
    insight: "Plant-based meals produce up to 70% fewer emissions than meat-based alternatives.",
    suggestion: "Try Meatless Mondays and incorporate more legumes, vegetables, and grains into your diet.",
    estimatedCarbonSaving: 8.4,
    priority: "medium",
  },
  {
    id: 4,
    category: "Transport",
    insight: "Public transportation reduces per-capita emissions by up to 75% compared to private vehicles.",
    suggestion: "Use public transportation for your daily commute at least 3 times per week.",
    estimatedCarbonSaving: 15.2,
    priority: "high",
  },
  {
    id: 5,
    category: "Shopping",
    insight: "Each online order generates packaging waste and delivery emissions.",
    suggestion: "Consolidate online orders and choose longer delivery windows to reduce rush shipping.",
    estimatedCarbonSaving: 3.5,
    priority: "low",
  },
  {
    id: 6,
    category: "Electricity",
    insight: "Switching to LED bulbs and unplugging idle devices can reduce standby electricity consumption.",
    suggestion: "Replace all incandescent bulbs with LEDs and use smart power strips to eliminate phantom loads.",
    estimatedCarbonSaving: 6.0,
    priority: "medium",
  },
];

export const AVAILABLE_BADGES = [
  { id: "green-beginner", name: "Green Beginner", description: "Complete your first carbon assessment", earned: true, earnedAt: "2024-01-15T00:00:00.000Z" },
  { id: "eco-warrior", name: "Eco Warrior", description: "Reduce emissions by 20% in a month", earned: true, earnedAt: "2024-02-10T00:00:00.000Z" },
  { id: "climate-hero", name: "Climate Hero", description: "Save 500 kg of CO2 total", earned: false, earnedAt: null },
  { id: "streak-master", name: "Streak Master", description: "Maintain a 7-day eco streak", earned: true, earnedAt: "2024-03-01T00:00:00.000Z" },
  { id: "tree-planter", name: "Tree Planter", description: "Plant 10 virtual trees through actions", earned: false, earnedAt: null },
  { id: "community-leader", name: "Community Leader", description: "Reach top 10 on the leaderboard", earned: false, earnedAt: null },
];
